# Generated by Django 4.2.6 on 2023-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='web',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
