# Generated by Django 4.2.2 on 2023-07-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='NIT',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
