# Generated by Django 4.2.2 on 2023-07-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(default='Activo', max_length=50),
        ),
    ]
